
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author saadghazal
 */
public class MouseKey_Practice extends javax.swing.JFrame {

    /**
     * Creates new form MouseKey_Practice
     */
    public MouseKey_Practice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickLabel = new javax.swing.JLabel();
        enterLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        pressedLabel = new javax.swing.JLabel();
        releasedLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clickLabel.setText("Mouse Click");
        clickLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickLabelMouseClicked(evt);
            }
        });

        enterLabel.setText("Mouse Enter");
        enterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterLabelMouseEntered(evt);
            }
        });

        exitLabel.setText("Mouse Exit");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        pressedLabel.setText("Mouse Pressed");
        pressedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressedLabelMousePressed(evt);
            }
        });

        releasedLabel.setText("Mouse Released");
        releasedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                releasedLabelMouseReleased(evt);
            }
        });

        TA.setEditable(false);
        TA.setColumns(20);
        TA.setRows(5);
        TA.setText("GHazal");
        TA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TAKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TAKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TAKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clickLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(releasedLabel)
                            .addComponent(pressedLabel)
                            .addComponent(exitLabel)
                            .addComponent(enterLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(clickLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pressedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(releasedLabel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickLabelMouseClicked
        // TODO add your handling code here:
    clickLabel.setForeground(Color.red);
    enterLabel.setForeground(Color.black);
    exitLabel.setForeground(Color.black);
    pressedLabel.setForeground(Color.black);
    releasedLabel.setForeground(Color.black);

        
    }//GEN-LAST:event_clickLabelMouseClicked

    private void enterLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterLabelMouseEntered
        // TODO add your handling code here:
        enterLabel.setForeground(Color.red);
         clickLabel.setForeground(Color.black);
    exitLabel.setForeground(Color.black);
    pressedLabel.setForeground(Color.black);
    releasedLabel.setForeground(Color.black);

    }//GEN-LAST:event_enterLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        // TODO add your handling code here:
        exitLabel.setForeground(Color.red);
        enterLabel.setForeground(Color.black);
    clickLabel.setForeground(Color.black);
    pressedLabel.setForeground(Color.black);
    releasedLabel.setForeground(Color.black);

    }//GEN-LAST:event_exitLabelMouseExited

    private void pressedLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressedLabelMousePressed
        // TODO add your handling code here:
        pressedLabel.setForeground(Color.red);
        enterLabel.setForeground(Color.black);
    exitLabel.setForeground(Color.black);
    clickLabel.setForeground(Color.black);
    releasedLabel.setForeground(Color.black);

    }//GEN-LAST:event_pressedLabelMousePressed

    private void releasedLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_releasedLabelMouseReleased
        // TODO add your handling code here:
       releasedLabel.setForeground(Color.red);
       enterLabel.setForeground(Color.black);
       exitLabel.setForeground(Color.black);
       pressedLabel.setForeground(Color.black);
       clickLabel.setForeground(Color.black);

    }//GEN-LAST:event_releasedLabelMouseReleased

    private void TAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TAKeyPressed
        // TODO add your handling code here:
        TA.setForeground(Color.red);
    }//GEN-LAST:event_TAKeyPressed

    private void TAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TAKeyTyped
        // TODO add your handling code here:
        TA.setForeground(Color.green);
    }//GEN-LAST:event_TAKeyTyped

    private void TAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TAKeyReleased
        // TODO add your handling code here:
        TA.setForeground(Color.yellow);
        
    }//GEN-LAST:event_TAKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MouseKey_Practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MouseKey_Practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MouseKey_Practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MouseKey_Practice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MouseKey_Practice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel clickLabel;
    private javax.swing.JLabel enterLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pressedLabel;
    private javax.swing.JLabel releasedLabel;
    // End of variables declaration//GEN-END:variables
}
